### ISSUE TITLE
ReferenceError: address is not defined

### ISSUE THREAD

**Issue by dacelee** [EasyX-Community/easyNOMP#136]
ReferenceError: address is not defined
    at Object.keys.forEach (/root/EasyNOMP/libs/paymentProcessor.js:491:40)
    at Array.forEach (native)
    at allWorkerShares.map (/root/EasyNOMP/libs/paymentProcessor.js:479:37)
    at Array.map (native)
    at Multi.callback (/root/EasyNOMP/libs/paymentProcessor.js:475:45)
    at multi_callback (/root/EasyNOMP/node_modules/redis/lib/multi.js:89:14)
    at Command.callback (/root/EasyNOMP/node_modules/redis/lib/multi.js:116:9)
    at normal_reply (/root/EasyNOMP/node_modules/redis/index.js:726:21)
    at RedisClient.return_reply (/root/EasyNOMP/node_modules/redis/index.js:824:9)
    at JavascriptRedis

**Comment by dacelee** [comment]
PaymentProcessor

**Comment by mooleshacat** [comment]
Yes I am working on payment processor right now.

**Is this master branch?** I just checked out master on the EasyX Pool and it seems to be working...

**If this is master branch I will look at it immediately.**

This is partly due to the fact I just started the repo, and until I get v1.1.4 finalized I have to push all changes from dev immediately, otherwise EasyNOMP is no different from the others. Once v1.1.4 finalized, there will be a first release, which will stabilize the master branch once again.

**Because the repository may have changed since you first cloned it, try:**
cd EasyNOMP
git checkout master
git pull
npm install

**Comment by mooleshacat** [comment]
If you look at http://miningpool.easyx.info:44420/stats/mogwaicoin there were a buildup of 12 blocks pending, those were because I was on the development branch...

You will notice as soon as I switched over to master branch payments started to process again, and it moved all 12 blocks out of pending. Pool loigs show 0 error in payment processor.

**Therefore; you either are using old code that has been updated since or you are checking out the development branch. Either case, the above fix should work. Let me know :)**

**A note to everyone,** until v1.1.4 is finalized and master branch is stable, there will be frequent updates to master branch, which may break NOMP. All you have to do is run another **git pull**

**Comment by dacelee** [comment]
I repair PaymentProcessor https://github.com/dacelee/BootNOMP/blob/master/libs/paymentProcessor.js

**Comment by mooleshacat** [comment]
@dacelee Not sure what you repaired if it was working to begin with... Is this a bug that you created in your own fork? Because I am not here to fix bugs that you create... If you are changing the source code, you are responsible for your own bugs.

If you have forked EasyNOMP you will need to re-merge with upstream (merge EasyNOMP -> your fork) again every so often to receive updates to your fork.

**Comment by dacelee** [comment]
thanks

**Comment by mooleshacat** [comment]
@everyone https://help.github.com/articles/syncing-a-fork/

Do that ^ every day until v1.1.4 is finalized. Once v1.1.4 is finalized, do that once per month.

**If you experience a bug in your fork:** Do the above process. Make sure the bug is not in your own code first. Then submit the issue to my issue tracker.

**If you are able to fix it in your code,** fix it and submit a pull request to upstream master (me). I will then send them off to zone117x, foxer666, and 1301313Y. **This process is the proper one, and credits your user account for the work all the way up to zone117x and you will be seen as a "contributor" on everyone's repo.**

This is partly my fault, as I have not yet got around to docs/FORKNOTES.md yet to add these instructions. The payment processor bugs are higher priority than documentation.

**Sorry about that!**
